package com.samsonova.projectarch.generator.templates

import com.samsonova.projectarch.models.AppArchitecture

object GradleTemplate {
    
    fun generate(architecture: AppArchitecture): String {
        return buildString {
            appendLine("plugins {")
            appendLine("    id(\"com.android.application\")")
            appendLine("    kotlin(\"android\")")
            appendLine("    kotlin(\"plugin.serialization\")")
            appendLine("    kotlin(\"kapt\")")
            appendLine("    id(\"com.google.dagger.hilt.android\")")
            appendLine("}")
            appendLine()
            appendLine("android {")
            appendLine("    namespace = \"${architecture.packageName}\"")
            appendLine("    compileSdk = ${architecture.targetSdkVersion}")
            appendLine()
            appendLine("    defaultConfig {")
            appendLine("        applicationId = \"${architecture.packageName}\"")
            appendLine("        minSdk = ${architecture.minSdkVersion}")
            appendLine("        targetSdk = ${architecture.targetSdkVersion}")
            appendLine("        versionCode = 1")
            appendLine("        versionName = \"1.0.0\"")
            appendLine("    }")
            appendLine()
            appendLine("    buildFeatures {")
            appendLine("        compose = true")
            appendLine("    }")
            appendLine()
            appendLine("    composeOptions {")
            appendLine("        kotlinCompilerExtensionVersion = \"1.5.3\"")
            appendLine("    }")
            appendLine("}")
            appendLine()
            appendLine("dependencies {")
            appendLine("    // Kotlin")
            appendLine("    implementation(\"org.jetbrains.kotlin:kotlin-stdlib:1.9.0\")")
            appendLine("    implementation(\"org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.1\")")
            appendLine("    implementation(\"org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.1\")")
            appendLine("    implementation(\"org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.0\")")
            appendLine()
            appendLine("    // Compose")
            appendLine("    implementation(\"androidx.compose.ui:ui:1.5.4\")")
            appendLine("    implementation(\"androidx.compose.material3:material3:1.1.2\")")
            appendLine("    implementation(\"androidx.lifecycle:lifecycle-viewmodel-compose:2.6.1\")")
            appendLine()
            appendLine("    // AndroidX")
            appendLine("    implementation(\"androidx.appcompat:appcompat:1.6.1\")")
            appendLine("    implementation(\"androidx.lifecycle:lifecycle-runtime-ktx:2.6.1\")")
            appendLine("    implementation(\"androidx.lifecycle:lifecycle-viewmodel-ktx:2.6.1\")")
            appendLine("    implementation(\"androidx.fragment:fragment-ktx:1.6.1\")")
            appendLine("    implementation(\"androidx.recyclerview:recyclerview:1.3.1\")")
            appendLine()
            appendLine("    // Room")
            appendLine("    implementation(\"androidx.room:room-runtime:2.5.2\")")
            appendLine("    implementation(\"androidx.room:room-ktx:2.5.2\")")
            appendLine("    kapt(\"androidx.room:room-compiler:2.5.2\")")
            appendLine()
            appendLine("    // Networking")
            appendLine("    implementation(\"com.squareup.retrofit2:retrofit:2.9.0\")")
            appendLine("    implementation(\"com.squareup.retrofit2:converter-kotlinx-serialization:2.9.0\")")
            appendLine("    implementation(\"com.squareup.okhttp3:okhttp:4.11.0\")")
            appendLine()
            appendLine("    // Hilt")
            appendLine("    implementation(\"com.google.dagger:hilt-android:2.47\")")
            appendLine("    kapt(\"com.google.dagger:hilt-compiler:2.47\")")
            appendLine("    implementation(\"androidx.hilt:hilt-navigation-compose:1.1.0\")")
            appendLine()
            appendLine("    // Testing")
            appendLine("    testImplementation(\"junit:junit:4.13.2\")")
            appendLine("    androidTestImplementation(\"androidx.test.ext:junit:1.1.5\")")
            appendLine("}")
        }
    }
}